name: Vercel Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: npm install -g vercel

    - name: Deploy to Vercel
      run: vercel . --prod --token ${{ secrets.VERCEL_TOKEN }}